theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

title: "Hamza Bendemra"
description: "AI & ML Lead • Engineering • Leadership"
url: "https://hamzabendemra.github.io"
baseurl: ""

# Minimal social links
github_username: HamzaBendemra
linkedin_username: hamzab

# Clean, minimal settings
show_excerpts: false
markdown: kramdown
highlighter: rouge

# Minimal header
header_pages:
  - about.md
  - blog.md