theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

title: "Hamza Bendemra"
description: "Machine Learning • Data Science • Leadership"
url: "https://hamzabendemra.github.io"
baseurl: ""

author:
  name: "Hamza Bendemra"
  email: "hamza@example.com"

# Minimal social links
github_username: HamzaBendemra
linkedin_username: hamzabendemra

# Clean, minimal settings
show_excerpts: false
paginate: 5
markdown: kramdown
highlighter: rouge

# Minimal header
header_pages:
  - about/index.md
  - projects.md