theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

title: "Hamza Bendemra"
description: "Machine Learning"
url: "https://hamzabendemra.github.io"
baseurl: ""

author:
  name: "Hamza Bendemra"
  email: "hamza@hamzabendemra.com"

# Minimal social links
github_username: HamzaBendemra
linkedin_username: hamzabendemra

# Clean, minimal settings
show_excerpts: false
markdown: kramdown
highlighter: rouge

# Minimal header
header_pages:
  - about.md
  - blog.md