theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

title: "Hamza Bendemra"
description: "AI & ML Lead"
url: "https://hamzabendemra.github.io"
baseurl: ""

# Social links
github_username: HamzaBendemra
linkedin_username: hamzab
medium_username: Hamza.b86
google_scholar_url: https://scholar.google.com/citations?user=r8Se7NwAAAAJ&hl=en
conversation_url: https://theconversation.com/profiles/hamza-bendemra-5289

# Clean, minimal settings
show_excerpts: false
markdown: kramdown
highlighter: rouge

# Minimal header
header_pages:
  - about.md
  - blog.md